import puppeteer from 'puppeteer-core'
const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox']})
const A=await browser.newPage()
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms))
const headName=()=>A.$$eval('.cm-name-input input',e=>e[0]?.value??'')
// 多轮：改名后不同停留时间再去团再返回
for(let waitMs of [200, 500, 1500]){
  const page=await browser.newPage()
  await page.goto('http://localhost:5173/cards',{waitUntil:'networkidle2',timeout:60000})
  await sleep(7000)
  await page.$$eval('.cm-card-item',(es)=>{es[0]?.click()})
  await sleep(400)
  await page.$$eval('.cm-name-input input',(es)=>{const el=es[0];const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'');el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()})
  await page.keyboard.type('新名'+waitMs)
  await page.keyboard.press('Tab')
  await sleep(waitMs)
  await page.goto('http://localhost:5173/party',{waitUntil:'networkidle2',timeout:60000})
  await sleep(1200)
  await page.goto('http://localhost:5173/cards',{waitUntil:'networkidle2',timeout:60000})
  await sleep(7000)
  await page.$$eval('.cm-card-item',(es)=>{es[0]?.click()})
  await sleep(400)
  const nm=await headName()
  console.log(`改名后等 ${waitMs}ms 再切团->回: header=${JSON.stringify(nm)} ${nm===('新名'+waitMs)?'✅':'❌ 回退'}`)
  await page.close()
}
await browser.close()
